[package]
name = "kms"
version = "0.1.0"
authors = [
    "Omer <omer@kzencorp.com>",
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["lib"]

[dependencies]
rust-gmp = "0.5.0"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
paillier = { git = "https://github.com/mortendahl/rust-paillier" }

[dependencies.cryptography-utils]
git = "https://github.com/KZen-networks/cryptography-utils"
features =  ["curvesecp256k1"]
tag = "v0.0.1"

[dependencies.multi-party-ecdsa]
git = "https://github.com/KZen-networks/multi-party-ecdsa"
tag = "v0.0.1"

[patch.crates-io]
rust-gmp = { version = "0.5.0", features = ["serde_support"], git = "https://github.com/KZen-networks/rust-gmp" }
